/**
 * AUTO-GENERATED input field definitions for n8n fixedCollection UI
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: pnpm generate:schemas
 * Generated: 2026-03-12T19:07:19.760Z
 */

export interface InputFieldDef {
	name: string;
	type: "string" | "number" | "boolean" | "options";
	required: boolean;
	description: string;
	placeholder?: string;
	options?: Array<{ name: string; value: string }>;
}

export const inputSchemas: Record<string, InputFieldDef[]> = {
	"instagram-comments": [
		{ name: "url", type: "string", required: true, description: "Instagram post URL", placeholder: "https://www.instagram.com/p/postId" },
	],
	"instagram-posts": [
		{ name: "url", type: "string", required: true, description: "Instagram post URL", placeholder: "https://www.instagram.com/p/postId" },
	],
	"instagram-profiles": [
		{ name: "url", type: "string", required: true, description: "Instagram profile URL", placeholder: "https://www.instagram.com/username" },
	],
	"instagram-reels": [
		{ name: "url", type: "string", required: true, description: "Instagram reel URL", placeholder: "https://www.instagram.com/reel/ABC123" },
	],
	"linkedin-companies": [
		{ name: "url", type: "string", required: true, description: "LinkedIn company URL", placeholder: "https://www.linkedin.com/company/company-name" },
	],
	"linkedin-jobs": [
		{ name: "url", type: "string", required: true, description: "LinkedIn job listings URL", placeholder: "https://www.linkedin.com/jobs/view/1234567890" },
	],
	"linkedin-people-search": [
		{ name: "url", type: "string", required: true, description: "LinkedIn search URL", placeholder: "https://www.linkedin.com/search/results/people/" },
		{ name: "first_name", type: "string", required: false, description: "First name to search by", placeholder: "John" },
		{ name: "last_name", type: "string", required: false, description: "Last name to search by", placeholder: "Doe" },
	],
	"linkedin-posts": [
		{ name: "url", type: "string", required: true, description: "LinkedIn post URL", placeholder: "https://www.linkedin.com/posts/username_activity" },
	],
	"linkedin-profiles": [
		{ name: "url", type: "string", required: true, description: "LinkedIn profile URL", placeholder: "https://www.linkedin.com/in/username" },
	],
	"tiktok-comments": [
		{ name: "url", type: "string", required: true, description: "Specific post URL", placeholder: "https://www.tiktok.com/@user/video/1234567890" },
	],
	"tiktok-posts": [
		{ name: "url", type: "string", required: true, description: "TikTok video URL", placeholder: "https://www.tiktok.com/@username/video/videoId" },
	],
	"tiktok-profiles": [
		{ name: "url", type: "string", required: true, description: "TikTok profile URL", placeholder: "https://www.tiktok.com/@username" },
	],
	"twitter-posts": [
		{ name: "url", type: "string", required: true, description: "Twitter/X post URL", placeholder: "https://twitter.com/username/status/tweetId" },
	],
	"twitter-profiles": [
		{ name: "url", type: "string", required: true, description: "Twitter/X profile URL", placeholder: "https://twitter.com/username" },
	],
	"youtube-channels": [
		{ name: "url", type: "string", required: true, description: "YouTube channel URL", placeholder: "https://www.youtube.com/@channelname" },
	],
	"youtube-comments": [
		{ name: "url", type: "string", required: true, description: "YouTube video URL", placeholder: "https://www.youtube.com/watch?v=videoId" },
		{ name: "load_replies", type: "number", required: false, description: "Number of replies to load per comment" },
		{ name: "num_of_comments", type: "number", required: false, description: "Maximum number of comments to fetch" },
		{ name: "sort_by", type: "options", required: false, description: "Sort order for comments", options: [{ name: "Top", value: "top" }, { name: "Newest", value: "newest" }] },
	],
	"youtube-videos": [
		{ name: "url", type: "string", required: true, description: "YouTube video URL", placeholder: "https://www.youtube.com/watch?v=videoId" },
	],
	"facebook-comments": [
		{ name: "url", type: "string", required: true, description: "Facebook post URL", placeholder: "https://www.facebook.com/username/posts/123456" },
	],
	"facebook-groups": [
		{ name: "url", type: "string", required: true, description: "Facebook group URL", placeholder: "https://www.facebook.com/groups/groupname" },
	],
	"facebook-posts": [
		{ name: "url", type: "string", required: true, description: "Facebook post URL", placeholder: "https://www.facebook.com/username/posts/123456" },
	],
	"facebook-profiles": [
		{ name: "url", type: "string", required: true, description: "Facebook profile or post URL", placeholder: "https://www.facebook.com/username" },
	],
	"facebook-reels": [
		{ name: "url", type: "string", required: true, description: "Facebook profile URL", placeholder: "https://www.facebook.com/username" },
	],
	"indeed-companies": [
		{ name: "url", type: "string", required: true, description: "Indeed company profile URL", placeholder: "https://www.indeed.com/cmp/..." },
	],
	"indeed-jobs": [
		{ name: "url", type: "string", required: true, description: "Indeed job listing URL", placeholder: "https://www.indeed.com/viewjob?jk=..." },
	],
	"glassdoor-companies": [
		{ name: "url", type: "string", required: true, description: "Glassdoor company profile URL", placeholder: "https://www.glassdoor.com/Overview/..." },
	],
	"glassdoor-jobs": [
		{ name: "url", type: "string", required: true, description: "Glassdoor job listing URL", placeholder: "https://www.glassdoor.com/job-listing/..." },
	],
	"glassdoor-reviews": [
		{ name: "url", type: "string", required: true, description: "Glassdoor company reviews URL", placeholder: "https://www.glassdoor.com/Reviews/..." },
	],
	"yelp-businesses": [
		{ name: "url", type: "string", required: true, description: "Yelp business profile URL", placeholder: "https://www.yelp.com/biz/..." },
	],
	"yelp-reviews": [
		{ name: "url", type: "string", required: true, description: "Yelp business reviews URL", placeholder: "https://www.yelp.com/biz/..." },
	],
	"github-repositories": [
		{ name: "url", type: "string", required: true, description: "GitHub repository URL", placeholder: "https://github.com/user/repo" },
	],
	"crunchbase-companies": [
		{ name: "url", type: "string", required: true, description: "Crunchbase company profile URL", placeholder: "https://www.crunchbase.com/organization/..." },
	],
	"tiktok-posts-by-url": [
		{ name: "url", type: "string", required: true, description: "Video URL", placeholder: "https://tiktok.com/@user/video/123" },
	],
	"tiktok-posts-by-profile": [
		{ name: "url", type: "string", required: true, description: "Profile URL", placeholder: "https://tiktok.com/@username" },
	],
	"tiktok-posts-by-search": [
		{ name: "url", type: "string", required: true, description: "Search URL", placeholder: "https://tiktok.com/search?q=keyword" },
	],
	"tiktok-shop": [
		{ name: "url", type: "string", required: true, description: "Shop Product URL", placeholder: "https://tiktok.com/shop/..." },
	],
	"tiktok-shop-categories": [
		{ name: "url", type: "string", required: true, description: "Shop Category URL", placeholder: "https://tiktok.com/shop/..." },
	],
	"facebook-pages-and-profiles": [
		{ name: "url", type: "string", required: true, description: "Page or Profile URL", placeholder: "https://facebook.com/pagename" },
	],
	"facebook-personal-profiles": [
		{ name: "url", type: "string", required: true, description: "Profile URL", placeholder: "https://facebook.com/username" },
	],
	"facebook-marketplace": [
		{ name: "url", type: "string", required: true, description: "Marketplace Listing URL", placeholder: "https://facebook.com/marketplace/item/123456" },
	],
	"facebook-events": [
		{ name: "url", type: "string", required: true, description: "Event URL", placeholder: "https://facebook.com/events/123456789" },
	],
	"facebook-company-reviews": [
		{ name: "url", type: "string", required: true, description: "Company Page URL", placeholder: "https://facebook.com/company-page" },
	],
	"google-maps-listings": [
		{ name: "url", type: "string", required: true, description: "Google Maps URL", placeholder: "https://google.com/maps/place/business-name" },
	],
	"google-maps-reviews": [
		{ name: "url", type: "string", required: true, description: "Google Maps URL", placeholder: "https://google.com/maps/place/business-name" },
	],
	"google-search-results": [
		{ name: "keyword", type: "string", required: true, description: "Search Query", placeholder: "best CRM software for startups" },
	],
	"google-search-ai": [
		{ name: "keyword", type: "string", required: true, description: "Search Query", placeholder: "what is the best project management tool" },
	],
	"google-shopping-products": [
		{ name: "url", type: "string", required: true, description: "Google Shopping Product URL", placeholder: "https://google.com/shopping/product/123" },
	],
	"google-shopping-search": [
		{ name: "keyword", type: "string", required: true, description: "Product Search Query", placeholder: "standing desk adjustable" },
	],
	"google-flights-search": [
		{ name: "url", type: "string", required: true, description: "Google Flights Search URL", placeholder: "https://google.com/travel/flights/search?tfs=..." },
	],
	"google-hotels-search": [
		{ name: "url", type: "string", required: true, description: "Google Hotels URL", placeholder: "https://google.com/travel/hotels/..." },
	],
	"zoominfo-companies": [
		{ name: "url", type: "string", required: true, description: "Company URL", placeholder: "https://zoominfo.com/c/company-name/123456" },
	],
	"trustpilot-reviews": [
		{ name: "url", type: "string", required: true, description: "Business Reviews URL", placeholder: "https://trustpilot.com/review/domain.com" },
	],
	"g2-reviews": [
		{ name: "url", type: "string", required: true, description: "Product Reviews URL", placeholder: "https://g2.com/products/product-name/reviews" },
	],
	"pitchbook-companies": [
		{ name: "url", type: "string", required: true, description: "Company URL", placeholder: "https://pitchbook.com/profiles/company/12345-67" },
	],
	"xing-profiles": [
		{ name: "url", type: "string", required: true, description: "Profile URL", placeholder: "https://xing.com/profile/firstname_lastname" },
	],
	"owler-companies": [
		{ name: "url", type: "string", required: true, description: "Company URL", placeholder: "https://owler.com/company/company-name" },
	],
	"martindale-lawyers": [
		{ name: "url", type: "string", required: true, description: "Attorney or Law Firm URL", placeholder: "https://martindale.com/attorney/firstname-lastname-12345" },
	],
	"ventureradar-companies": [
		{ name: "url", type: "string", required: true, description: "Company URL", placeholder: "https://ventureradar.com/company/company-name/123" },
	],
	"trustradius-reviews": [
		{ name: "url", type: "string", required: true, description: "Product Reviews URL", placeholder: "https://trustradius.com/products/product-name/reviews" },
	],
};
